<?php
/**
 * Created by PhpStorm.
 * User: claudio
 * Date: 29/08/2016
 * Time: 13:08
 */

namespace Base\Navigation\Factory;


use Zend\Navigation\Service\DefaultNavigationFactory;

class SecondaryNavigationFactory extends DefaultNavigationFactory {


    protected function getName()
    {
        return 'secondary'; // TODO: Change the autogenerated stub
    }


} 