<?php
/**
 * Created by PhpStorm.
 * User: claudio
 * Date: 29/08/2016
 * Time: 13:08
 */

namespace Base\Navigation\Factory;


use Zend\Navigation\Service\DefaultNavigationFactory;

class SpecialNavigationFactory extends DefaultNavigationFactory {


    protected function getName()
    {

        return 'special'; // TODO: Change the autogenerated stub
    }


} 