<form method="POST" name="Users" class="form-horizontal" id="Manager" role="form" action="&#x2F;update-password">
    <fieldset>
        <legend>FORMULARI DE ALTERAÇÃO DE SENHA</legend>
        <div class="row">
            <div class="col-xs-12 col-md-6 col-md-offset-3 col-xs-offset-0">
                <fieldset>
                    <legend>GERAL</legend>
                    #id#
                    <div class=""> <label class="control-label" for="password">
                            {{password}}
                        </label><div class="valid&#x20;password">
                            #password#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="usr_password_confirm">
                            {{usr_password_confirm}}
                        </label><div class="valid&#x20;usr_password_confirm">
                            #usr_password_confirm#
                        </div>
                    </div>
                    #security#


                    <hr>
                    <button type="submit" name="save" class="btn&#x20;btn-primary" value="">BTN_SAVE_LABEL</button>
                    <a class="btn&#x20;btn-danger" href="&#x2F;admin">VOLTAR<span class="glyphicon&#x20;glyphicon-share-alt"></span></a>
                    <div class="clearfix"></div>
                </fieldset>
            </div>
            </div>
        <div class="clearfix"></div>
    </fieldset>
</form>
