#open-form#
<fieldset>
    <legend>FORMULARI DE MANUTENÇÃO</legend>
    <div class="row">
    	<div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
            <fieldset>
                <legend>GERAL</legend>
                #geral#
                <hr>
                #comando#
                <div class="clearfix"></div>
            </fieldset>
    	</div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <fieldset>
                <legend>FORMULARI DE ADICIONAL</legend>
               <div class="row">
                   <div class="col-md-12">
                       #controller#
                       <div class="clearfix"></div>
                   </div>
                   <div class="col-md-12">
                      #datas#
                       <div class="clearfix"></div>
                   </div>
               </div>
            </fieldset>
        </div>
    </div>
    <div class="clearfix"></div>
</fieldset>
#close-form#
