<?php
/**
 * Created by PhpStorm.
 * User: Call
 * Date: 17/08/2016
 * Time: 00:14
 */

namespace Home\Controller;


use Interop\Container\ContainerInterface;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

abstract class AbstractController extends AbstractActionController {

    /**
     * @var $containerInterface ContainerInterface
     */
    protected $containerInterface;
    protected $table;
    protected $model;
    protected $form;
    protected $filter;
    protected $route;
    protected $controller;
    protected $ation;
    protected $id;
    protected $page;
    protected $data;

    /**
     * @param MvcEvent $e
     * @return mixed
     */
    public function onDispatch(MvcEvent $e)
    {
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    /**
     * @param ContainerInterface $containerInterface
     */
    abstract  function __construct(ContainerInterface $containerInterface);

    /**
     * @return mixed
     */
    public function getTable()
    {
        return $this->containerInterface->get($this->table);
    }

    /**
     * @return mixed
     */
    public function getModel()
    {
        return $this->containerInterface->get($this->model);
    }

    /**
     * @return mixed
     */
    public function getForm()
    {
        return $this->containerInterface->get($this->form);
    }

    /**
     * @return mixed
     */
    public function getFilter()
    {
        return $this->containerInterface->get($this->filter);
    }

    /**
     * @return mixed
     */
    public function getData()
    {
        if($this->params()->fromPost()){
            $this->data=array_merge_recursive($this->params()->fromPost(),$this->params()->fromFiles());
        }
        return $this->data;
    }

    public function accessdenyAction()
    {
        $view=new ViewModel();
        return $view;
    }



} 