<?php echo $this->doctype() ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo$this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo$this->headLink(['rel' => 'shortcut icon', 'type' => '/assets_admin/image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets_admin/img/favicon.ico'])
            ->prependStylesheet($this->basePath('/assets_admin/css/style.css'))
            ->prependStylesheet($this->basePath('/assets_admin/css/pnotify.custom.min.css'))
            ->prependStylesheet($this->basePath('/assets_admin/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('/assets_admin/css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('/assets_admin/css/bootstrap.min.css'))
        ?>


    </head>
    <body id="app">
       <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?=$this->basePath('/assets_admin/img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Base\Module::VERSION ?>"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                        <?= $this->navigation('special')->setAcl($this->UserIdentity()->getAuthAcl())
                            ->setRole((string)$this->UserIdentity()->getAuthAcl()->getRoleDefaul())
                            ->menu()->setUlClass('nav navbar-nav')->setPartial('partial/navbar-default');?>

                </div>
            </div>
        </nav>
        <div class="container"><p>
                <?php echo $this->navigation('special')->breadcrumbs() // cool separator with newline
                ?>
        </p>
         <?= $this->content ?>
             <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
       <!-- Scripts -->
       <?php echo $this->headScript()
           //->prependFile($this->basePath('/assets_admin/js/vue.search.js'))
           //->prependFile($this->basePath('/assets_admin/js/vue.min.js'))
           ->prependFile($this->basePath('/assets_admin/js/notify.init.js'))
           ->prependFile($this->basePath('/assets_admin/js/fileUpload.js'))
           ->prependFile($this->basePath('/assets_admin/js/form.init.js'))
           ->prependFile($this->basePath('/assets_admin/js/Funcoes.js'))
           ->prependFile($this->basePath('/assets_admin/js/jquery.sprintf.js'))
           ->prependFile($this->basePath('/assets_admin/js/jquery.form.min.js'))
           ->prependFile($this->basePath('/assets_admin/js/pnotify.custom.min.js'))
           ->prependFile($this->basePath('/assets_admin/js/bootstrap.min.js'))
           ->prependFile($this->basePath('/assets_admin/js/jquery-3.1.0.min.js'))
       ?>
    </body>
</html>
