    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            #images#
            <div class="caption">
                <h3>#title#</h3>
                <p>#description#</p>
                <p>
                    <a href="#rota-editar#" class="btn btn-primary btn-xs" role="button"><i class="fa fa-edit"></i> <span class="hidden-xs">EDITAR</span> </a>
                    <a href="#rota-excluir#" class="btn btn-danger btn-xs excluir" role="button"><i class="fa fa-trash-o"></i> <span class="hidden-xs">EXCLUIR</span></a></p>
            </div>
        </div>
    </div>