<form method="POST" class="form-horizontal" id="Manager" enctype="multipart&#x2F;form-data" role="form" action="&#x2F;configuracao&#x2F;finalizar">
    <fieldset>
        <legend>FORMULARI DE MANUTENÇÃO</legend>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
                <fieldset>
                    <legend>GERAL</legend>
                    #id#
                    #asset_id#
                    #codigo#
                    #empresa#
                    <div class=""> <label class="control-label" for="title">
                            {{title}}
                        </label><div class="valid&#x20;title">
                            #title#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="fantasia">
                            {{fantasia}}
                        </label><div class="valid&#x20;fantasia">
                            #fantasia#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="phone">
                            {{title}}
                        </label><div class="valid&#x20;phone">
                            #phone#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="email">
                            {{email}}
                        </label><div class="valid&#x20;email">
                            #email#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="facebook">
                            {{facebook}}
                        </label><div class="valid&#x20;facebook">
                            #facebook#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="twitter">
                            {{twitter}}
                        </label><div class="valid&#x20;twitter">
                            #twitter#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="cidade">
                            {{cidade}}
                        </label><div class="valid&#x20;cidade">
                            #cidade#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="bairro">
                            {{bairro}}
                        </label><div class="valid&#x20;bairro">
                            #bairro#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="endereco">
                            {{endereco}}
                        </label><div class="valid&#x20;endereco">
                            #endereco#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="latitude">
                            {{latitude}}
                        </label><div class="valid&#x20;latitude">
                            #latitude#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="longetude">
                            {{longetude}}
                        </label><div class="valid&#x20;longetude">
                            #longetude#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="description">
                            {{description}}
                        </label><div class="valid&#x20;description">
                            #description#
                        </div>

                    </div>
                    #security#

                    <hr>
                    <button type="submit" name="save" class="btn&#x20;btn-primary" value="">BTN_SAVE_LABEL</button>
                    <button type="submit" name="save_copy" class="btn&#x20;btn-warning" value="">BTN_SAVE_COPY_LABEL</button>
                    <a class="btn&#x20;btn-danger" href="&#x2F;configuracao">VOLTAR<span class="glyphicon&#x20;glyphicon-share-alt"></span></a>

                    <div class="clearfix"></div>
                </fieldset>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <fieldset>
                    <legend>FORMULARI DE ADICIONAL</legend>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="">     <div class="img-add images"><label class="control-label" for="images">
                                        {{images}}
                                    </label>
                                    #imagePriview#
                                </div>
                                <div class="valid&#x20;images">
                                    #images#
                                </div>
                                <input type="file" class="atachament" id="atachament" name="atachament">
                                <p class="help-block">Max. 32MB</p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="col-md-12">
                            <div class=""> <label class="control-label" for="access">
                                    {{access}}
                                </label><div class="valid&#x20;access">
                                    #access#
                                </div>
                            </div>
                            <div class=""> <label class="control-label" for="state">
                                    {{state}}
                                </label><div class="valid&#x20;state">
                                    #state#
                                </div>
                            </div>
                            <div class=""> <label class="control-label" for="created">
                                    {{created}}
                                </label><div class="valid&#x20;created">
                                    #created#
                                </div>

                            </div>
                            <div class=""> <label class="control-label" for="modified">
                                    {{modified}}
                                </label><div class="valid&#x20;modified">
                                    #modified#
                                </div>

                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="clearfix"></div>
    </fieldset>
</form>